# RITIS API for XD Segments EXAMPLE

### Download data for a single day

In [1]:
api_key = open("key.txt", "r").read().strip()

from RITIS_API import RITIS_Downloader

updater = RITIS_Downloader(
    api_key=api_key,
    download_path='Data', #data will be saved in this directory
    segments_path='sample_XD_segments.txt', #path to csv file containing segment ids
    start_time='06:00:00', #default is '00:00:00
    end_time='19:59:00', #default is '23:59:00'
    bin_size=15, #Enter 5, 10, 15(default), or 60
    units='seconds', #'seconds' or 'minutes'
    columns=['speed', 'reference_speed', 'travel_time_minutes'], #a list including any of ["speed","average_speed","reference_speed","travel_time_minutes","confidence_score","cvalue"]
    confidence_score=[30], #a list including any of [10,20,30]
    last_run_path='last_run.txt', #path for text file containing last run datetime
    verbose=2, #0: no print, 1: print only important messages, 2: print all messages
    sleep_time=20
    ) 

updater.single_download('2024-08-01', '2024-08-02', 'test') #start_date, end_date, job_name

Initializing RITIS_Downloader
Loaded 2 XD segments

In [2]:
# read the file to confirm it worked
import pandas as pd
df = pd.read_parquet('Data/test.parquet')
df

,xd_id,measurement_tstamp,speed,reference_speed,travel_time_seconds
0,1236860943,2024-08-01 06:00:00,22.37,24.0,13.36
1,1236860943,2024-08-01 06:15:00,21.27,24.0,14.04
2,1236860943,2024-08-01 06:30:00,24.42,24.0,12.24
3,1236860943,2024-08-01 06:45:00,22.13,24.0,13.50
4,1236860943,2024-08-01 07:00:00,23.09,24.0,12.94
...,...,...,...,...,...
92,1236893704,2024-08-01 17:15:00,55.12,51.0,36.50
93,1236893704,2024-08-01 17:30:00,53.08,51.0,37.90
94,1236893704,2024-08-01 17:45:00,55.00,51.0,36.58
95,1236893704,2024-08-01 18:00:00,53.44,51.0,37.65
96,1236893704,2024-08-01 18:15:00,52.00,51.0,38.69

### Download data through yesterday

In [ ]:
api_key = open("key.txt", "r").read().strip()

from RITIS_API import RITIS_Downloader

# NEED TO TEST THIS, MAY NOT WORK YET