# RITIS API for XD Segments EXAMPLE

### Download data for a single day

In [1]:
api_key = open("key.txt", "r").read().strip()

from RITIS_API import RITIS_Downloader

updater = RITIS_Downloader(
    api_key=api_key,
    download_path='Data', #data will be saved in this directory
    segments_path='sample_XD_segments.txt', #path to csv file containing segment ids
    start_time='06:00:00', #default is '00:00:00
    end_time='19:59:00', #default is '23:59:00'
    bin_size=15, #Enter 5, 10, 15(default), or 60
    units='seconds', #'seconds' or 'minutes'
    columns=['speed', 'reference_speed', 'travel_time_minutes'], #a list including any of ["speed","average_speed","reference_speed","travel_time_minutes","confidence_score","cvalue"]
    confidence_score=[30], #a list including any of [10,20,30]
    last_run_path='last_run.txt', #path for text file containing last run datetime
    verbose=2, #0: no print, 1: print only important messages, 2: print all messages
    sleep_time=20
    ) 

updater.single_download('2024-08-01', '2024-08-02', 'test') #start_date, end_date, job_name

Initializing RITIS_Downloader
Loaded 2 XD segments

In [2]:
# read the file to confirm it worked
import pandas as pd
df = pd.read_parquet('Data/test.parquet')
df

,xd_id,measurement_tstamp,speed,reference_speed,travel_time_seconds
0,1236860943,2024-08-01 06:00:00,22.37,24.0,13.36
1,1236860943,2024-08-01 06:15:00,21.27,24.0,14.04
2,1236860943,2024-08-01 06:30:00,24.42,24.0,12.24
3,1236860943,2024-08-01 06:45:00,22.13,24.0,13.50
4,1236860943,2024-08-01 07:00:00,23.09,24.0,12.94
...,...,...,...,...,...
92,1236893704,2024-08-01 17:15:00,55.12,51.0,36.50
93,1236893704,2024-08-01 17:30:00,53.08,51.0,37.90
94,1236893704,2024-08-01 17:45:00,55.00,51.0,36.58
95,1236893704,2024-08-01 18:00:00,53.44,51.0,37.65
96,1236893704,2024-08-01 18:15:00,52.00,51.0,38.69

### Download data through yesterday

In [1]:
api_key = open("key.txt", "r").read().strip()

from RITIS_API import RITIS_Downloader

updater = RITIS_Downloader(
    api_key=api_key,
    download_path='Data', #data will be saved in this directory
    segments_path='sample_XD_segments.txt', #path to csv file containing segment ids
    start_time='06:00:00', #default is '00:00:00
    end_time='19:59:00', #default is '23:59:00'
    bin_size=15, #Enter 5, 10, 15(default), or 60
    units='seconds', #'seconds' or 'minutes'
    columns=['speed', 'reference_speed', 'travel_time_minutes'], #a list including any of ["speed","average_speed","reference_speed","travel_time_minutes","confidence_score","cvalue"]
    confidence_score=[30], #a list including any of [10,20,30]
    last_run_path='last_run.txt', #path for text file containing last run datetime
    verbose=2, #0: no print, 1: print only important messages, 2: print all messages
    sleep_time=60
    ) 

updater.daily_download()

Initializing RITIS_Downloader
Loaded 2 XD segments
Starting daily download
Getting dates for daily download
Dates to process: ['2024-09-26', '2024-09-27', '2024-09-28', '2024-09-29']
Submitting job: start_date=2024-09-26, end_date=2024-09-27, name=daily_2024-09-26
Submitting job with UUID: c3789170-aec7-453b-84e6-4856a896fed3
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2635
Job Progress: 0.0%
Job Progress: 0.0%
Job Progress: 0.0%
Job Progress: 8.54%
Job Progress: 20.63%
Job Progress: 28.83%
Job Progress: 44.34%
Job Progress: 100.0%
Downloading and processing results for UUID: c3789170-aec7-453b-84e6-4856a896fed3
Saved parquet file: Data\daily_2024-09-26.parquet
Submitting job: start_date=2024-09-27, end_date=2024-09-28, name=daily_2024-09-27
Submitting job with UUID: acdb0ddf-d6ef-4146-b98b-b22740410886
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2638
Job Progress: 0.0%
Job Progress: 26.32%
Job Progress: 42.25%
Job Progress: 100.0%
Downloading and processing results for UUID: acdb0ddf-d6ef-4146-b98b-b22740410886
Saved parquet file: Data\daily_2024-09-27.parquet
Submitting job: start_date=2024-09-28, end_date=2024-09-29, name=daily_2024-09-28
Submitting job with UUID: aef56813-cafc-4544-84d5-c83991275a1b
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2642
Job Progress: 0.0%
Job Progress: 8.69%
Job Progress: 24.36%
Job Progress: 36.93%
Job Progress: 100.0%
Downloading and processing results for UUID: aef56813-cafc-4544-84d5-c83991275a1b
Saved parquet file: Data\daily_2024-09-28.parquet
Submitting job: start_date=2024-09-29, end_date=2024-09-30, name=daily_2024-09-29
Submitting job with UUID: 28a2b922-66b1-4dd2-bbcc-e86e3714004d
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2645
Job Progress: 0.0%
Job Progress: 30.45%
Job Progress: 47.07%
Job Progress: 100.0%
Downloading and processing results for UUID: 28a2b922-66b1-4dd2-bbcc-e86e3714004d
Saved parquet file: Data\daily_2024-09-29.parquet
Daily download completed

# INRIX Real-Time Speed Example

In [1]:
from INRIX_API import INRIX_Downloader

inrix_downloader = INRIX_Downloader(
    app_id_path='API_Keys/INRIX_appId.txt',
    hash_token_path='API_Keys/INRIX_hashToken.txt',
    token_path='API_Keys/INRIX_token.json',
    segments_path='sample_XD_segments.txt',
    verbose=2  # Set to 2 for more detailed output, 1 for less, 0 for no output
)

speed_data = inrix_downloader.get_speed_data()
speed_data

INRIX_Downloader: Initializing INRIX_Downloader
INRIX_Downloader: Reading file: API_Keys/INRIX_appId.txt
INRIX_Downloader: Reading file: API_Keys/INRIX_hashToken.txt
INRIX_Downloader: Reading segments from: sample_XD_segments.txt
INRIX_Downloader: Loaded 2 segments
INRIX_Downloader: Loading or refreshing token
INRIX_Downloader: Token loaded from file
INRIX_Downloader: Current time (UTC): 2024-10-01 16:07:55.520451+00:00, Token expiry: 2024-10-02 00:33:20.004257+00:00
INRIX_Downloader: Time until token expiry: 8:25:24.483806
INRIX_Downloader: Getting speed data
INRIX_Downloader: Requesting data for segments 1 to 2
INRIX_Downloader: Received data for 2 segments
INRIX_Downloader: Total segments data received: 2

         code type  speed  average
0  1236893704  XDS     47       53
1  1236860943  XDS     18       21

## INRIX Speed Data Example - Over 1000 segments

In [3]:
# Example using lots of sements from ODOT Signals
from INRIX_API import INRIX_Downloader

inrix_downloader = INRIX_Downloader(
    app_id_path='API_Keys/INRIX_appId.txt',
    hash_token_path='API_Keys/INRIX_hashToken.txt',
    token_path='API_Keys/INRIX_token.json',
    segments_path='//scdata2/signalshar/Data_Analysis/RITIS_Massive_Data_Downloader/XD_segments.txt',
    verbose=1  # Set to 2 for more detailed output, 1 for less, 0 for no output
)

speed_data = inrix_downloader.get_speed_data()
speed_data

INRIX_Downloader: Loaded 5590 segments
INRIX_Downloader: Getting speed data
INRIX_Downloader: Total segments data received: 5491

            code type  speed  average segmentClosed
0     1236893704  XDS   47.0       53           NaN
1     1236860943  XDS   19.0       21           NaN
2     1236893725  XDS   25.0       24           NaN
3     1236992050  XDS   13.0       16           NaN
4     1236926528  XDS   16.0       15           NaN
...          ...  ...    ...      ...           ...
5486   440958961  XDS   22.0       19           NaN
5487   440958964  XDS   16.0       18           NaN
5488   440958968  XDS   12.0       12           NaN
5489   440958973  XDS   24.0       23           NaN
5490   385974270  XDS   15.0       13           NaN

[5491 rows x 5 columns]

We have the segmentClosed column only because these segments are from an outdated map version :(

Fear not, the GeometryScrapper is here to help! (next section)

# UPDATE SEGMENTS LIST & GEOMETRIES

This will take a list of lat/long points and return segment geometries within a specified radius of them

In [1]:
import pandas as pd

signals_df = pd.read_parquet('Map_Data/signals.parquet') 
# extract Latitudes and Longitude into a list of tuples
signals = list(zip(signals_df['Latitude'], signals_df['Longitude']))
# Print first few signal lat/longs
print(signals[:3])

[(46.0242029974689, -123.91167466706), (45.9791874021872, -123.92671351604), (45.9930911891673, -123.920617724861)]

In [2]:
from Geometry_Scraper import GeometryScraper

# Will ask for Cookie, which you can copy from a request in your browser use dev tools
scraper = GeometryScraper()
geometry_data = scraper.process_locations(signals, buffer_size=50) #buffer size in yards
# Save the data
geometry_data.to_parquet('Map_Data/segment_geometry.parquet')
geometry_data

Processing 1874 locations in batches of 500
Processing batch 1
Processing batch 2
Processing batch 3
Processing batch 4
Combining all batches into a single DataFrame

,zip,country,segID,bearing,county,state,roadName,frc,startLatitude,endLongitude,startLongitude,endLatitude,miles,intersectingRoads,tmc,direction,road,firstname,roadNumber,coordinates
0,97225,USA,448842059,N,WASHINGTON,OR,SW SCHOLLS FERRY RD,4,45.48626,-122.74823,-122.74878,45.48653,0.032524,[SW OLESON RD],448842059,N,SW SCHOLLS FERRY RD,SW OLESON RD,NaN,"[[-122.74878, 45.48626], [-122.74833, 45.48648..."
1,97051,USA,1237027426,E,COLUMBIA,OR,GABLE RD,4,45.84865,-122.81877,-122.83160,45.84729,0.669561,[OLD PORTLAND RD],1237027426,E,GABLE RD,OLD PORTLAND RD,NaN,"[[-122.8316, 45.84865], [-122.83134, 45.84852]..."
2,97141,USA,1236850628,E,TILLAMOOK,OR,3RD ST,3,45.45632,-123.83823,-123.84315,45.45680,0.245709,"[1ST ST, OR-6]",1236850628,E,3RD ST,1ST ST,6,"[[-123.84315, 45.45632], [-123.84209, 45.45632..."
3,97223,USA,429027767,S,WASHINGTON,OR,SW 72ND AVE,4,45.42697,-122.75163,-122.75161,45.42551,0.100938,[SW HUNZIKER RD],429027767,S,SW 72ND AVE,SW HUNZIKER RD,NaN,"[[-122.75161, 45.42697], [-122.75163, 45.42674..."
4,97209,USA,125230407,W,MULTNOMAH,OR,NW COUCH ST,5,45.52358,-122.68824,-122.68725,45.52357,0.047931,[NW 17TH AVE],125230407,W,NW COUCH ST,NW 17TH AVE,NaN,"[[-122.68725, 45.52358], [-122.68795, 45.52357..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9142,97035,USA,440920611,N,CLACKAMAS,OR,BOONES FERRY RD,4,45.42448,-122.70734,-122.70788,45.42497,0.042801,[COUNTRY CLUB RD],440920611,N,BOONES FERRY RD,COUNTRY CLUB RD,NaN,"[[-122.70788, 45.42448], [-122.70734, 45.42497]]"
9143,97070,USA,440961397,W,CLACKAMAS,OR,SW WILSONVILLE RD,4,45.30314,-122.76032,-122.75748,45.30301,0.138983,"[SW TOWN CENTER LOOP, SW MEMORIAL DR]",440961397,W,SW WILSONVILLE RD,SW TOWN CENTER LOOP,NaN,"[[-122.75748, 45.30314], [-122.75764, 45.30314..."
9144,97306,USA,1236963253,E,MARION,OR,KUEBLER BLVD SE,4,44.88285,-123.05109,-123.06122,44.88122,0.517086,[],1236963253,E,KUEBLER BLVD SE,None,NaN,"[[-123.06122, 44.88285], [-123.06074, 44.88289..."
9145,97045,USA,448838435,N,CLACKAMAS,OR,5TH ST,4,45.34979,-122.60570,-122.60092,45.35444,0.438761,[],448838435,N,5TH ST,None,NaN,"[[-122.60092000000004, 45.34978999999999], [-1..."
9146,97035,USA,448834173,E,CLACKAMAS,OR,KRUSE WAY,4,45.41677,-122.71602,-122.71931,45.41564,0.177647,[LOWER BOONES FERRY RD],448834173,E,KRUSE WAY,LOWER BOONES FERRY RD,NaN,"[[-122.71931, 45.41677], [-122.7185, 45.41649]..."