# RITIS API for XD Segments EXAMPLE

### Download data for a single day

In [1]:
api_key = open("key.txt", "r").read().strip()

from RITIS_API import RITIS_Downloader

updater = RITIS_Downloader(
    api_key=api_key,
    download_path='Data', #data will be saved in this directory
    segments_path='sample_XD_segments.txt', #path to csv file containing segment ids
    start_time='06:00:00', #default is '00:00:00
    end_time='19:59:00', #default is '23:59:00'
    bin_size=15, #Enter 5, 10, 15(default), or 60
    units='seconds', #'seconds' or 'minutes'
    columns=['speed', 'reference_speed', 'travel_time_minutes'], #a list including any of ["speed","average_speed","reference_speed","travel_time_minutes","confidence_score","cvalue"]
    confidence_score=[30], #a list including any of [10,20,30]
    last_run_path='last_run.txt', #path for text file containing last run datetime
    verbose=2, #0: no print, 1: print only important messages, 2: print all messages
    sleep_time=20
    ) 

updater.single_download('2024-08-01', '2024-08-02', 'test') #start_date, end_date, job_name

Initializing RITIS_Downloader
Loaded 2 XD segments

In [2]:
# read the file to confirm it worked
import pandas as pd
df = pd.read_parquet('Data/test.parquet')
df

,xd_id,measurement_tstamp,speed,reference_speed,travel_time_seconds
0,1236860943,2024-08-01 06:00:00,22.37,24.0,13.36
1,1236860943,2024-08-01 06:15:00,21.27,24.0,14.04
2,1236860943,2024-08-01 06:30:00,24.42,24.0,12.24
3,1236860943,2024-08-01 06:45:00,22.13,24.0,13.50
4,1236860943,2024-08-01 07:00:00,23.09,24.0,12.94
...,...,...,...,...,...
92,1236893704,2024-08-01 17:15:00,55.12,51.0,36.50
93,1236893704,2024-08-01 17:30:00,53.08,51.0,37.90
94,1236893704,2024-08-01 17:45:00,55.00,51.0,36.58
95,1236893704,2024-08-01 18:00:00,53.44,51.0,37.65
96,1236893704,2024-08-01 18:15:00,52.00,51.0,38.69

### Download data through yesterday

In [1]:
api_key = open("key.txt", "r").read().strip()

from RITIS_API import RITIS_Downloader

updater = RITIS_Downloader(
    api_key=api_key,
    download_path='Data', #data will be saved in this directory
    segments_path='sample_XD_segments.txt', #path to csv file containing segment ids
    start_time='06:00:00', #default is '00:00:00
    end_time='19:59:00', #default is '23:59:00'
    bin_size=15, #Enter 5, 10, 15(default), or 60
    units='seconds', #'seconds' or 'minutes'
    columns=['speed', 'reference_speed', 'travel_time_minutes'], #a list including any of ["speed","average_speed","reference_speed","travel_time_minutes","confidence_score","cvalue"]
    confidence_score=[30], #a list including any of [10,20,30]
    last_run_path='last_run.txt', #path for text file containing last run datetime
    verbose=2, #0: no print, 1: print only important messages, 2: print all messages
    sleep_time=60
    ) 

updater.daily_download()

Initializing RITIS_Downloader
Loaded 2 XD segments
Starting daily download
Getting dates for daily download
Dates to process: ['2024-09-26', '2024-09-27', '2024-09-28', '2024-09-29']
Submitting job: start_date=2024-09-26, end_date=2024-09-27, name=daily_2024-09-26
Submitting job with UUID: c3789170-aec7-453b-84e6-4856a896fed3
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2635
Job Progress: 0.0%
Job Progress: 0.0%
Job Progress: 0.0%
Job Progress: 8.54%
Job Progress: 20.63%
Job Progress: 28.83%
Job Progress: 44.34%
Job Progress: 100.0%
Downloading and processing results for UUID: c3789170-aec7-453b-84e6-4856a896fed3
Saved parquet file: Data\daily_2024-09-26.parquet
Submitting job: start_date=2024-09-27, end_date=2024-09-28, name=daily_2024-09-27
Submitting job with UUID: acdb0ddf-d6ef-4146-b98b-b22740410886
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2638
Job Progress: 0.0%
Job Progress: 26.32%
Job Progress: 42.25%
Job Progress: 100.0%
Downloading and processing results for UUID: acdb0ddf-d6ef-4146-b98b-b22740410886
Saved parquet file: Data\daily_2024-09-27.parquet
Submitting job: start_date=2024-09-28, end_date=2024-09-29, name=daily_2024-09-28
Submitting job with UUID: aef56813-cafc-4544-84d5-c83991275a1b
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2642
Job Progress: 0.0%
Job Progress: 8.69%
Job Progress: 24.36%
Job Progress: 36.93%
Job Progress: 100.0%
Downloading and processing results for UUID: aef56813-cafc-4544-84d5-c83991275a1b
Saved parquet file: Data\daily_2024-09-28.parquet
Submitting job: start_date=2024-09-29, end_date=2024-09-30, name=daily_2024-09-29
Submitting job with UUID: 28a2b922-66b1-4dd2-bbcc-e86e3714004d
Job submission response: 200
Job submitted successfully. Job ID: application_1726936226001_2645
Job Progress: 0.0%
Job Progress: 30.45%
Job Progress: 47.07%
Job Progress: 100.0%
Downloading and processing results for UUID: 28a2b922-66b1-4dd2-bbcc-e86e3714004d
Saved parquet file: Data\daily_2024-09-29.parquet
Daily download completed

# INRIX Real-Time Speed Example

In [1]:
from INRIX_API import INRIX_Downloader

inrix_downloader = INRIX_Downloader(
    app_id_path='API_Keys/INRIX_appId.txt',
    hash_token_path='API_Keys/INRIX_hashToken.txt',
    token_path='API_Keys/INRIX_token.json',
    segments_path='sample_XD_segments.txt',
    verbose=2  # Set to 2 for more detailed output, 1 for less, 0 for no output
)

speed_data = inrix_downloader.get_speed_data()
speed_data

INRIX_Downloader: Initializing INRIX_Downloader
INRIX_Downloader: Reading file: API_Keys/INRIX_appId.txt
INRIX_Downloader: Reading file: API_Keys/INRIX_hashToken.txt
INRIX_Downloader: Reading segments from: sample_XD_segments.txt
INRIX_Downloader: Loaded 2 segments
INRIX_Downloader: Loading or refreshing token
INRIX_Downloader: Token loaded from file
INRIX_Downloader: Current time (UTC): 2024-10-01 16:07:55.520451+00:00, Token expiry: 2024-10-02 00:33:20.004257+00:00
INRIX_Downloader: Time until token expiry: 8:25:24.483806
INRIX_Downloader: Getting speed data
INRIX_Downloader: Requesting data for segments 1 to 2
INRIX_Downloader: Received data for 2 segments
INRIX_Downloader: Total segments data received: 2

         code type  speed  average
0  1236893704  XDS     47       53
1  1236860943  XDS     18       21

## INRIX Speed Data Example - Over 1000 segments

In [3]:
# Example using lots of sements from ODOT Signals
from INRIX_API import INRIX_Downloader

inrix_downloader = INRIX_Downloader(
    app_id_path='API_Keys/INRIX_appId.txt',
    hash_token_path='API_Keys/INRIX_hashToken.txt',
    token_path='API_Keys/INRIX_token.json',
    segments_path='//scdata2/signalshar/Data_Analysis/RITIS_Massive_Data_Downloader/XD_segments.txt',
    verbose=1  # Set to 2 for more detailed output, 1 for less, 0 for no output
)

speed_data = inrix_downloader.get_speed_data()
speed_data

INRIX_Downloader: Loaded 5590 segments
INRIX_Downloader: Getting speed data
INRIX_Downloader: Total segments data received: 5491

            code type  speed  average segmentClosed
0     1236893704  XDS   47.0       53           NaN
1     1236860943  XDS   19.0       21           NaN
2     1236893725  XDS   25.0       24           NaN
3     1236992050  XDS   13.0       16           NaN
4     1236926528  XDS   16.0       15           NaN
...          ...  ...    ...      ...           ...
5486   440958961  XDS   22.0       19           NaN
5487   440958964  XDS   16.0       18           NaN
5488   440958968  XDS   12.0       12           NaN
5489   440958973  XDS   24.0       23           NaN
5490   385974270  XDS   15.0       13           NaN

[5491 rows x 5 columns]

We need to update our segments list to the latest map version :(

Coming soon!

In [12]:
speed_data[speed_data['segmentClosed'].notnull()]

            code type  speed  average segmentClosed
355    125536209  XDS    NaN       14          True
1320  1237000437  XDS    NaN       20          True
2505   448838513  XDS    NaN       29          True
4044  1237015107  XDS    NaN       25          True
4066  1237015146  XDS    NaN       23          True
4267  1236950866  XDS    NaN       25          True
4285  1236951044  XDS    NaN       21          True
5175  1237022957  XDS    NaN       22          True